repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: "v6.0.0"
    hooks:
      - id: check-added-large-files
      - id: check-case-conflict
      - id: check-json
        exclude: \.vscode
      - id: check-merge-conflict
      - id: check-toml
      - id: check-yaml
      - id: detect-private-key
      - id: end-of-file-fixer
      - id: fix-byte-order-marker
      - id: trailing-whitespace

  - repo: local
    hooks:
      # Requires GITHUB_TOKEN env var to avoid API rate limits

      - id: pin-github-action
        name: pin GHA SHAs in main action
        language: node
        entry: pin-github-action
        additional_dependencies: ["pin-github-action"]
        files: ^action.ya?ml
        types_or: [yaml]

      - id: pin-github-action
        name: pin GHA SHAs in workflows
        language: node
        entry: pin-github-action
        args: ["--allow", "griceturrble/precommit-checks-action"]
        additional_dependencies: ["pin-github-action"]
        files: ^\.github/workflows/
        types_or: [yaml]

  - repo: https://github.com/rbubley/mirrors-prettier
    rev: "v3.9.5"
    hooks:
      - id: prettier
        types_or: [markdown, json, yaml, html]
