name: "Pre-commit checks"
description: "Runs pre-commit checks"
author: "Galen Rice"
inputs:
  python_version:
    description: "Python version to use."
    default: "3.12"
  pre_commit_version:
    description: "Pre-commit version to use."
    default: "4.0.1"

runs:
  using: "composite"
  steps:
    - name: "Setup Python"
      uses: actions/setup-python@v5
      with:
        python-version: ${{ inputs.python_version }}

    - name: "Install pre-commit"
      run: |
        python -m pip install pre-commit==${{ inputs.pre_commit_version }}

        # Debug: show packages we installed
        PACKAGES=$(python -m pip freeze --local)
        echo "::debug::Packages installed:"
        echo "::debug::${PACKAGES}"
      shell: bash

    - uses: actions/cache@v4
      with:
        path: ~/.cache/pre-commit
        key: python-${{ inputs.python_version }}|pre-commit-${{ inputs.pre_commit_version }}|${{ hashFiles('.pre-commit-config.yaml') }}

    - name: "Run pre-commit checks"
      run: pre-commit run --show-diff-on-failure --all-files --color=always
      shell: bash

branding:
  icon: "check-circle"
  color: "orange"
