name: "Pre-commit checks"
description: "Runs pre-commit checks"
inputs:
  python_version:
    description: "Python version to use."
    type: string
    required: false
    default: "3.12"
  pre_commit_version:
    type: string
    description: "Pre-commit version to use."
    required: false
    default: "4.0.1"

runs:
  using: "composite"
  steps:
    - name: "Setup Python"
      uses: actions/setup-python@v5
      with:
        python-version: ${{ inputs.python_version }}

    - name: "Install pre-commit"
      run: python -m pip install pre-commit==${{ inputs.pre_commit_version }}
      shell: bash

    - run: python -m pip freeze --local
      shell: bash

    - uses: actions/cache@v4
      with:
        path: ~/.cache/pre-commit
        key: pre-commit-${{ inputs.pre_commit_version }}|${{ hashFiles('.pre-commit-config.yaml') }}

    - name: "Run pre-commit checks"
      run: pre-commit run --show-diff-on-failure --color=always
      shell: bash
