# Run pre-commit autoupdate and create a pull request with any updates

name: pre-commit autoupdate

on:
  workflow_dispatch:
  schedule:
    # Every Mon 11AM UTC (~6AM US/Eastern)
    - cron: "0 11 * * 1"

jobs:
  update:
    permissions:
      contents: write
      pull-requests: write
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7
      - uses: griceturrble/precommit-autoupdate-action@301af7e8305b5c2969f3604843e8e55dc7db0e26 # v4
        with:
          pr_title: "[Draft] pre-commit autoupdate"
