# Run pre-commit autoupdate and create a pull request with any updates

name: pre-commit autoupdate

on:
  workflow_dispatch:
  schedule:
    # Every Mon 11AM UTC (~6AM US/Eastern)
    - cron: "0 11 * * 1"

jobs:
  update:
    permissions:
      contents: write
      pull-requests: write
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7
      - uses: griceturrble/precommit-autoupdate-action@2c412d5dbc31c544c21af10a415b58040483b788 # v4
        with:
          pr_title: "[Draft] pre-commit autoupdate"
