# Run pre-commit autoupdate and create a pull request with any updates

name: pre-commit autoupdate

on:
  workflow_dispatch:
  schedule:
    # Every Mon 11AM UTC (~6AM US/Eastern)
    - cron: "0 11 * * 1"

jobs:
  update:
    permissions:
      contents: write
      pull-requests: write
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: griceturrble/precommit-autoupdate-action@v1
        with:
          pr_title: "[Draft] pre-commit autoupdate"
